const jobs = [
  {
    "jobKey": "drillers offsider traineeship|topdrill pty ltd|perth wa|https://www.seek.com.au/job/92390540",
    "title": "Drillers Offsider Traineeship",
    "company": "Topdrill Pty Ltd",
    "location": "Perth WA",
    "roster": "2:1",
    "category": "drillers-offsider",
    "experience": "entry",
    "beginnerFriendly": true,
    "tickets": [
      "HR Licence",
      "C Class Licence",
      "National Police Check",
      "First Aid",
      "Working at Heights"
    ],
    "salary": "$120",
    "source": "SEEK",
    "dateAdded": "2026-05-29",
    "lastChecked": "",
    "status": "Active",
    "applyUrl": "https://www.seek.com.au/job/92390540"
  },
  {
    "jobKey": "administrator - site|macmahon|perth wa|https://www.seek.com.au/job/92371098",
    "title": "Administrator - Site",
    "company": "Macmahon",
    "location": "Perth WA",
    "roster": "8:6",
    "category": "site-administrator",
    "experience": "entry",
    "beginnerFriendly": true,
    "tickets": [],
    "salary": "Not listed",
    "source": "SEEK",
    "dateAdded": "2026-05-29",
    "lastChecked": "",
    "status": "Active",
    "applyUrl": "https://www.seek.com.au/job/92371098"
  },
  {
    "jobKey": "fifo utility - fulltime 2:1 swings|ironmerge pty ltd|perth wa (remote)|https://www.seek.com.au/job/91839886",
    "title": "FIFO Utility - Fulltime 2:1 Swings",
    "company": "IronMerge Pty Ltd",
    "location": "Perth WA (Remote)",
    "roster": "2:1",
    "category": "utility-worker",
    "experience": "entry",
    "beginnerFriendly": true,
    "tickets": [
      "C Class Licence",
      "National Police Check",
      "Forklift Licence",
      "RSA",
      "Food Safety"
    ],
    "salary": "$87500",
    "source": "SEEK",
    "dateAdded": "2026-05-29",
    "lastChecked": "",
    "status": "Active",
    "applyUrl": "https://www.seek.com.au/job/91839886"
  },
  {
    "jobKey": "entry level drillers offsider - fifo | surface & underground | $120k+|niche resources group|perth wa|https://www.seek.com.au/job/92384594",
    "title": "Entry Level Drillers Offsider - FIFO | Surface & Underground | $120k+",
    "company": "Niche Resources Group",
    "location": "Perth WA",
    "roster": "2/1",
    "category": "drillers-offsider",
    "experience": "entry",
    "beginnerFriendly": true,
    "tickets": [
      "HR Licence",
      "C Class Licence",
      "National Police Check"
    ],
    "salary": "$120",
    "source": "SEEK",
    "dateAdded": "2026-05-29",
    "lastChecked": "2026-08-02",
    "status": "Active",
    "applyUrl": "https://www.seek.com.au/job/93362281"
  },
  {
    "jobKey": "trade assistant | 2:1 fifo roster|polaris engineering|perth wa|https://www.seek.com.au/job/92386542",
    "title": "Trade Assistant | 2:1 FIFO Roster",
    "company": "Polaris Engineering",
    "location": "Perth WA",
    "roster": "2:1",
    "category": "trade-assistant",
    "experience": "entry",
    "beginnerFriendly": true,
    "tickets": [
      "HR Licence",
      "C Class Licence",
      "White Card",
      "Working at Heights",
      "Confined Space",
      "Forklift Licence"
    ],
    "salary": "$53 per hour",
    "source": "SEEK",
    "dateAdded": "2026-05-29",
    "lastChecked": "2026-08-02",
    "status": "Active",
    "applyUrl": "https://www.seek.com.au/job/93210814"
  },
  {
    "jobKey": "entry level nipper operator|evolution mining|kalgoorlie, kalgoorlie, goldfields & esperance wa|https://www.seek.com.au/job/92386776",
    "title": "Entry Level Nipper Operator",
    "company": "Evolution Mining",
    "location": "Kalgoorlie, Kalgoorlie, Goldfields & Esperance WA",
    "roster": "7:7",
    "category": "underground-nipper",
    "experience": "entry",
    "beginnerFriendly": true,
    "tickets": [
      "C Class Licence"
    ],
    "salary": "$120",
    "source": "SEEK",
    "dateAdded": "2026-05-29",
    "lastChecked": "2026-08-02",
    "status": "Active",
    "applyUrl": "https://www.seek.com.au/job/93595133"
  },
  {
    "jobKey": "roving administrator|byrnecut australia pty ltd|perth airport, perth wa|https://www.seek.com.au/job/92365173",
    "title": "Roving Administrator",
    "company": "Byrnecut Australia Pty Ltd",
    "location": "Perth Airport, Perth WA",
    "roster": "Not listed",
    "category": "site-administrator",
    "experience": "entry",
    "beginnerFriendly": false,
    "tickets": [
      "C Class Licence",
      "National Police Check"
    ],
    "salary": "Not listed",
    "source": "SEEK",
    "dateAdded": "2026-05-29",
    "lastChecked": "",
    "status": "Active",
    "applyUrl": "https://www.seek.com.au/job/92365173"
  },
  {
    "jobKey": "entry level drillers offsider - fifo | surface & underground | $120k+|niche resources group|perth wa|https://www.seek.com.au/job/92384594",
    "title": "Entry Level Drillers Offsider - FIFO | Surface & Underground | $120k+",
    "company": "Niche Resources Group",
    "location": "Perth WA",
    "roster": "2/1",
    "category": "underground-nipper",
    "experience": "entry",
    "beginnerFriendly": true,
    "tickets": [
      "HR Licence",
      "C Class Licence",
      "National Police Check"
    ],
    "salary": "$120",
    "source": "SEEK",
    "dateAdded": "2026-05-29",
    "lastChecked": "",
    "status": "Active",
    "applyUrl": "https://www.seek.com.au/job/92384594"
  },
  {
    "jobKey": "multiple trades & leadership roles – fifo & dido mining shutdowns across wa|marlu group|perth wa|https://www.seek.com.au/job/92383119",
    "title": "MULTIPLE TRADES & LEADERSHIP ROLES – FIFO & DIDO MINING SHUTDOWNS ACROSS WA",
    "company": "Marlu Group",
    "location": "Perth WA",
    "roster": "2:1",
    "category": "trade-assistant",
    "experience": "entry",
    "beginnerFriendly": true,
    "tickets": [
      "White Card",
      "Working at Heights",
      "Confined Space"
    ],
    "salary": "Not listed",
    "source": "SEEK",
    "dateAdded": "2026-05-29",
    "lastChecked": "",
    "status": "Active",
    "applyUrl": "https://www.seek.com.au/job/92383119"
  }
];
